"""added test capability to module

Revision ID: 260ade4c3a6a
Revises: 51fa6b7926d5
Create Date: 2021-05-12 13:16:14.590186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260ade4c3a6a'
down_revision = '51fa6b7926d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###
