"""Added defaults to user statistics

Revision ID: 28afd7cd0879
Revises: a9658cf3badc
Create Date: 2021-05-02 16:09:07.027169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28afd7cd0879'
down_revision = 'a9658cf3badc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    # ### end Alembic commands ###
