"""admin statistics

Revision ID: 51fa6b7926d5
Revises: 8061fe242c2a
Create Date: 2021-05-09 22:59:32.244615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fa6b7926d5'
down_revision = '8061fe242c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_right', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('times_submitted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('times_submitted')
        batch_op.drop_column('times_right')

    # ### end Alembic commands ###
