"""empty message

Revision ID: 64b04b790a71
Revises: 28afd7cd0879
Create Date: 2021-05-04 21:22:08.790997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b04b790a71'
down_revision = '28afd7cd0879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_activity_name'), ['name'])

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_module_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_module_name'), type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_activity_name'), type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
