"""added time remaining

Revision ID: 709e91acfe7e
Revises: b94acd647dcc
Create Date: 2021-05-15 23:04:49.933790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709e91acfe7e'
down_revision = 'b94acd647dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_remaining', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.drop_column('time_remaining')

    # ### end Alembic commands ###
