"""fixed data types and foreign keys

Revision ID: a9658cf3badc
Revises: 2c54348d24a9
Create Date: 2021-04-29 22:05:19.633553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9658cf3badc'
down_revision = '2c54348d24a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activityDependency', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'activity', ['parent'], ['id'])
        batch_op.create_foreign_key(None, 'activity', ['child'], ['id'])

    with op.batch_alter_table('moduleDependency', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'module', ['child'], ['id'])
        batch_op.create_foreign_key(None, 'module', ['parent'], ['id'])

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_timestamp'))

    with op.batch_alter_table('moduleDependency', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activityDependency', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
