"""added save for database

Revision ID: bf69ce5fcd5d
Revises: 17d6b517a81a
Create Date: 2021-05-06 23:35:55.595383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf69ce5fcd5d'
down_revision = '17d6b517a81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
