"""added time stop

Revision ID: dcb80532f7bf
Revises: 709e91acfe7e
Create Date: 2021-05-15 23:13:40.799067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb80532f7bf'
down_revision = '709e91acfe7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stop', sa.Integer(), nullable=True))
        batch_op.drop_column('time_remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_remaining', sa.INTEGER(), nullable=True))
        batch_op.drop_column('time_stop')

    # ### end Alembic commands ###
