"""Added Foreign Key from activity to module

Revision ID: efdc45fc6149
Revises: 84a75e01357f
Create Date: 2021-05-05 09:58:22.016150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdc45fc6149'
down_revision = '84a75e01357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activity_module_id_module'), 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_module_id_module'), type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
